version: "3.8"
services:
    web:
        image: luki88/appcourse-web
        ports:
            - 80:80
        networks:
            - homework
        depends_on:
            - db
    db:
        image: luki88/appcourse-db
        networks:
            - homework
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    homework:
